### PR TITLE
Add typing effect

### PR DESCRIPTION
**Pull request by gabrieldemian**
- Typing effect is completed
- Added a few comments inside the code

### CODE REVIEW

**Comment by gabrieldemian** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by andrewgazelka** [comment]
Weird that the CLA Assistant is still failing. Let me look into this.

**Comment by andrewgazelka** [comment]
rebasing. Ideally I wouldn't have to do this, but I am trying to look at the diff in my IDE and it usually does best when there is one commit. Hopefully this is not an issue since you are working right now.

**Review by andrewgazelka — APPROVED** [review]
LGTM going to add another commit to fix some stuff up

**Pull request merged**
